apiVersion: apps/v1
kind: Deployment
metadata:
  name: waw-frontend
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: waw-frontend
  template:
    metadata:
      labels:
        app: waw-frontend
    spec:
      containers:
        - name: waw-frontend
          image: logangibler/waw-frontend:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"